debug: true

app_name: "My Boilerplate for Go Backend services"
port: 2000

csrf_token: "32-byte-long-auth-key"
maxReqBodySize: 10000000 

production:
  stripe_key: 

development:
  stripe_key: "test secret key"